image:
  - Ubuntu
  - Visual Studio 2017
version: 2.2.0-{build}
clone_depth: 10
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  PGPASSWORD: Password12! # Used by psql on Windows.
  POSTGIS_EXE: postgis-bundle-pg10x64-setup-2.4.4-1.exe
  NoPackageAnalysis: true  # Suppresses warning about SemVer 2.0.0 version suffixes when packing
for:
-
  matrix:
    only:
      - image: Visual Studio 2017
  cache:
    - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
    - $(POSTGIS_EXE)
  services:
    - postgresql101
-
  matrix:
    only:
      - image: Ubuntu
  cache:
    - ~/.nuget/packages -> **/*.csproj
  services:
    - postgresql
install:
  - sh: sudo sh .build/install.sh
  - pwsh: .build/install.ps1
before_build:
  - pwsh: .build/before_build.ps1
  - pwsh: dotnet restore -v Minimal --disable-parallel
build_script:
  - pwsh: dotnet pack src/EFCore.PG/EFCore.PG.csproj -c Release
  - pwsh: dotnet pack src/EFCore.PG.NodaTime/EFCore.PG.NodaTime.csproj -c Release
  - pwsh: dotnet pack src/EFCore.PG.NTS/EFCore.PG.NTS.csproj -c Release
test_script:
  - pwsh: dotnet test test/EFCore.PG.Tests/EFCore.PG.Tests.csproj -c Release
  - pwsh: dotnet test test/EFCore.PG.Plugins.FunctionalTests/EFCore.PG.Plugins.FunctionalTests.csproj -c Release
  - pwsh: dotnet test test/EFCore.PG.FunctionalTests/EFCore.PG.FunctionalTests.csproj -c Release
artifacts:
  - path: 'src\**\*.nupkg'
deploy:
  # Deploy on CI_WINDOWS because the build order is Linux -> Windows.
  - provider: Environment
    name: MyGet Unstable
    on:
      deploy_myget_unstable: true
      CI_WINDOWS: true
  - provider: Environment
    name: MyGet Stable
    on:
      deploy_myget_stable: true
      CI_WINDOWS: true
  - provider: Environment
    name: EFCore.PG Github
    on:
      deploy_github_release: true
      CI_WINDOWS: true