image: Visual Studio 2017 Preview
version: 2.0.0-{build}
services:
  - postgresql
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    Test__Npgsql__DefaultConnection: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
shallow_clone: true
install:
  - ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')
  # Install .NET Core 2.0
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "install-dotnet.ps1"
  - ps: .\install-dotnet.ps1 -Version 2.0.0
before_build:
  - dotnet --info
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - msbuild /p:Configuration=Debug
  - msbuild /p:Configuration=Release
  - dotnet pack src\EFCore.PG\EFCore.PG.csproj -c Release --version-suffix ci-%PADDED_BUILD_NUMBER%
test_script:
  - cd test\EFCore.PG.Tests && dotnet xunit && cd ..\..\
  - cd test\EFCore.PG.FunctionalTests && dotnet xunit && cd ..\..\
  - cd test\EFCore.PG.Design.FunctionalTests && dotnet xunit && cd ..\..\
artifacts:
  - path: 'src\EFCore.PG\bin\**\*.nupkg'
  - path: 'src\EFCore.PG.Design\bin\**\*.nupkg'
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/npgsql-unstable/api/v2/package
    api_key:
      secure: kiMn9uBvgMa5EtEmTIhNBFUfyatiATnhkgx5Xj/1EsmKTtEkUv+hJAQs0L3VGzPw
    artifact: /.*\.nupkg/
    skip_symbols: true
    #skip_symbols: false
    #symbol_server: https://your.symbol.server/feed

